steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/celerodevops/alpine-postgres12', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/celerodevops/alpine-postgres12']
images: ['gcr.io/celerodevops/alpine-postgres12']
